pycsp: Implement Python binding for csp_sfp_send
GomSpace/libcsp pull request #15
Opened 2024-07-01 06:49 UTC by jichgom

The function sets internal flags on csp_conn_t that are not accessible in Python, making it hard to implement in Python.

There is also a commit included in this that implements freeing of `Py_Buffer` in the bindings. Have a look at the commit message for more details

2024-09-03 01:39 UTC, mmeisner reviewed
nice bugfixes!

2024-09-03 01:39 UTC, mmeisner commented on src/bindings/python/pycsp.c
> +        : PyErr_Error("csp_sfp_send()", res);
```
    if (res != CSP_ERR_NONE) {
        return PyErr_Error("csp_sfp_send()", res);
    }
    Py_RETURN_NONE;
```
ref: https://docs.python.org/3/c-api/none.html#c.Py_RETURN_NONEnone.html#c.Py_RETURN_NONE)

2024-09-03 01:39 UTC, mmeisner commented on src/bindings/python/pycsp.c
>      Py_RETURN_NONE;
```
   PyBuffer_Release(&inbuf);
   if (res != CSP_ERR_NONE) {
        return PyErr_Error("csp_cmp_poke()", res);
   }
   Py_RETURN_NONE;
```

2024-09-03 01:56 UTC, mmeisner requested changes

2024-09-03 01:56 UTC, mmeisner commented on src/bindings/python/pycsp.c
More complete commit message:
```
The `csp_sfp_send()` function is missing from the Python interface.
Furthermore, it is impossible to otherwise implement in pure Python using
the existing `pycsp` functions because:
The `csp_sfp_send()` function sets `CSP_FFRAG` flag in each packet header before
`csp_send()`. That flag cannot be set using`pycsp_connect` so it is in effect an
internal flag.

2024-09-03 06:59 UTC, jichgom commented on src/bindings/python/pycsp.c
> +        : PyErr_Error("csp_sfp_send()", res);
This doesn't explain why I should change the code. Yea `Py_RETURN_NONE` is an option, but it doesn't seem like it's better or worse.

2024-09-03 17:17 UTC, mmeisner approved these changes

2024-09-03 17:20 UTC, mmeisner commented
@Wramberg, hvad er det nu for en pseudo person `product-sw`? man skal sætte på review?
Completion kommer ikke op med noget?

2024-09-04 05:43 UTC, Wramberg commented
Teamet skal stå som collaborator på repo ellers kan man ikke vælge det som reviewer

2024-09-12 12:27 UTC, mmeisner commented
@Wramberg, will anyone from products review this?
We also need a release afterwards...

2024-09-12 13:39 UTC, larseje commented
I recently added bindings to `csp_recvfrom` and `buffree`:
https://github.com/GomSpace/libgscsp/commit/0f0d49e7aeb73b6295d938e09bc53c1471e82fc5
https://github.com/GomSpace/libgscsp/commit/4dfe81613a8dcdd0666dc2ed10d65b4e16edbbd8

I added those binding to libgscsp to avoid having this intermediate libcsp fork with minimal changes compared to upstream.

I know we have stuff in GomSpace/libcsp already, but just wanted to avoid keep feeling up the fork. (I'd rather see it gone, with libgscsp only wrapping libcsp/libcsp).

Any chance the new binding here can be implemented in libgscsp instead?

2024-11-29 08:46 UTC, closed without merging